TestSibers/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Services.Entities;
using Services.Services;
using TestSibers.Models;

namespace TestSibers.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IMapper _mapper;
        public EmployeeController(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<EmployeeServiceEntity, EmployeeModel>();
                cfg.CreateMap<EmployeeModel, EmployeeServiceEntity>();
            });
            _mapper = config.CreateMapper();
        }
        
        public ActionResult Index()
        {
            return View(_mapper.Map<ICollection<EmployeeServiceEntity>, ICollection<EmployeeModel>>(_employeeService.GetAll()).ToList());
        }

        public ActionResult NewEmployee(EmployeeModel employee)
        {
            return View(employee);
        }

        public RedirectResult Delete(int id)
        {
            _employeeService.Delete(id);
            return Redirect("~/Employee");
        }

        public RedirectResult Create(EmployeeModel employee)
        {
            _employeeService.Add(_mapper.Map<EmployeeModel,EmployeeServiceEntity>(employee));
            return Redirect("~/Employee");
        }

        public ActionResult Edit(int id, EmployeeModel employee)
        {
            return View(_mapper.Map<EmployeeServiceEntity, EmployeeModel>(_employeeService.GetById(id)));
        }

        public RedirectResult Save(EmployeeModel employee)
        {
            _employeeService.Update(_mapper.Map<EmployeeModel,EmployeeServiceEntity>(employee));
            return Redirect("~/Employee");
        }
    }
}

TestSibers/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using Services.Entities;
using Services.Services;
using TestSibers.Models;
using WebGrease.Css.Extensions;

namespace TestSibers.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService _projectService;
        private readonly IEmployeeService _employeeService;
        private readonly IMapper _mapper;
        public ProjectController(IProjectService projectService, IEmployeeService employeeService)
        {
            _projectService = projectService;
            _employeeService = employeeService;

            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<ProjectServiceEntity, ProjectModel>();
                cfg.CreateMap<ProjectModel, ProjectServiceEntity>();
            });
            _mapper = config.CreateMapper();
        }

        public ActionResult Index(string searchFilter, DateTime? startDate, DateTime? endDate, int? fromPrior, int? toPrior, SortProject sort = 0)
        {
            var projects = _projectService.GetAllProject(searchFilter, sort);

            if (startDate != null && endDate != null)
                projects = projects.Where(c => c.StartDate >= startDate && c.EndDate <= endDate).ToList();

            if (fromPrior != null && toPrior != null)
                projects = projects.Where(c => c.Priority >= fromPrior && c.Priority <= toPrior).ToList();

            return View(_mapper.Map<ICollection<ProjectServiceEntity>, ICollection<ProjectModel>>(projects.ToList()));

        }

        public ActionResult NewProject(ProjectModel project)
        {
            return View(project);
        }

        public ActionResult Edit(int id, ProjectModel project)
        {

            return View(_mapper.Map<ProjectServiceEntity, ProjectModel>(_projectService.GetById(id)));
        }

        public ActionResult FullProject(int? id)
        {
            if (id == null)
                return HttpNotFound();
            var project = _mapper.Map<ProjectServiceEntity, ProjectModel>(_projectService.GetById(id.Value));
            ViewBag.employees = _mapper.Map<ICollection<EmployeeServiceEntity>, ICollection<EmployeeModel>>(_projectService.GetAllEmployees(id.Value));
            if (project != null)
                return View(project);
            return null;
        }

        [HttpPost]
        public string SearchManager(string str)
        {
            if (Request.IsAjaxRequest())
                if (str.Length == 0)
                {
                    var employees = _employeeService.GetAll().Take(10);
                    var request = new StringBuilder();
                    employees.ForEach(c => request.Append("<li>" + c.Id + " " + c.Surname + " " + c.FirstName + " " + c.Patronymic + "</li>"));
                    return request.ToString();
                }
                else
                {
                    var employees = _employeeService.GetAll().ToList().Where(c =>
                    {
                        if (c.FirstName.ToLower().Contains(str.ToLower()) || c.Surname.ToLower().Contains(str.ToLower()) || c.Patronymic.ToLower().Contains(str.ToLower()))
                            return true;
                        return false;
                    });
                    var request = new StringBuilder();
                    employees.Take(10).ForEach(c => request.Append("<li>" + c.Id + " " + c.Surname + " " + c.FirstName + " " + c.Patronymic + "</li>"));
                    return request.ToString();
                }
            return null;
        }

        public RedirectResult Create(ProjectModel project)
        {
            _projectService.Add(_mapper.Map<ProjectModel, ProjectServiceEntity>(project));
            return Redirect("~/Project");
        }

        public RedirectResult Delete(int id)
        {
            _projectService.Delete(id);
            return Redirect("~/Project");
        }

        public RedirectResult Bind(int? projectId, int? ProjectManagerId)
        {
            if (projectId != null && ProjectManagerId != null)
                _projectService.Bind(projectId.Value, ProjectManagerId.Value);

            return Redirect($"~/Project/FullProject?id={projectId}");
        }

        public RedirectResult UnBind(int projectId, int employeeId)
        {
            _projectService.UnBind(projectId, employeeId);
            return Redirect($"~/Project/FullProject?id={projectId}");
        }

        public RedirectResult Save(ProjectModel project)
        {
            _projectService.Update(_mapper.Map<ProjectModel, ProjectServiceEntity>(project));
            return Redirect("~/project");
        }
    }
}

TestSibers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Sibers</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Test Sibers</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Главная", "Index", "Home", null, new { @class = "nav-link" })
                    <!--<a class="nav-link" href="">Главная</a>-->
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Проекты</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        @Html.ActionLink("Добавить новый проект", "NewProject", "Project", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Управление проектами", "Index", "Project", null, new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Сотрудники</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        @Html.ActionLink("Добавить нового сотрудника", "NewEmployee", "Employee", null, new { @class = "dropdown-item" })
                        @Html.ActionLink("Управление сотрудниками", "Index", "Employee", null, new { @class = "dropdown-item" })
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    @*Html.ActionLink("Домашняя страница", "Index", "Home")*@

    <main role="main" class="container">
        @RenderBody()
    </main>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/addProject")
    @RenderSection("scripts", required: false)
</body>
</html>